# Generated by Django 5.1 on 2026-06-17 09:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo_seguimiento', models.CharField(max_length=8, unique=True)),
                ('nombre_cliente', models.CharField(blank=True, max_length=255, null=True)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En proceso'), ('enviado', 'Enviado'), ('completado', 'Completado')], default='pendiente', max_length=20)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pedidos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=255)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('variante', models.CharField(blank=True, max_length=255, null=True)),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalles_pedido', to='productos.producto')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='pedidos.pedido')),
            ],
            options={
                'db_table': 'detalles_pedido',
            },
        ),
    ]
